GunShop/Models/BuyModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GunShop.Models
{
    public class BuyModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int GunId { get; set; }
        public int inStock { get; set; }
        public bool Tracer { get; set; }
        public bool Hollowpoint { get; set; }
        public bool Incendiary { get; set; }
    }
}

GunShop/Models/IndexPageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GunShop.Infrastructure.Data;
using GunShop.Domain.Core;
using GunShop.Domain.Core.OrderAggregate;

namespace GunShop.Models
{
    public class IndexPageViewModel
    {
        

        public Gun _Gun { get; set; }
        public List<Gun> Gun { get; set; }
        public Dictionary<int,Gun > Guns { get; set; }
        public Dictionary<int, Warehouse> Ware { get; set; }
        public List<PriceComponent> PriceComponents { get; set; }
        public List<int> ReservedGuns { get; set; }

    }
}

GunShop/Models/OrderViewModel.cs
using GunShop.Domain.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GunShop.Models
{
    public class OrderViewModel
    {
        public Gun Gun { get; set; }
        public Order Order { get; set; }
        
    }
}

GunShop/Models/ReservationViewModel.cs
using GunShop.Domain.Core;
using GunShop.Domain.Core.OrderAggregate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GunShop.Models
{
    public class ReservationViewModel
    {
        public DateTime Date { get; set; }       
        public Reservation Reservation { get; set; }
        public Gun gun { get; set; }
        public List<PriceComponent> PriceComponents { get; set; }
    }
}

GunShop/Controllers/GunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GunShop.Domain.Core;
using GunShop.Domai.Interfaces;
using GunShop.Services.Interfaces;
using GunShop.Models;
using GunShop.Infrastructure.Data;

namespace GunShop.Controllers
{
    public class GunController : Controller
    {
        private IGunRepository gunrepo;
        private IPriceCalculation price;
        private IOrderRepository orderrep;
        private IReservationService resserv;
        private IReservationRepository resrepo;
        public GunController(IGunRepository r, IPriceCalculation p,IOrderRepository o,IReservationService rs,IReservationRepository rr)
        {
            gunrepo = r;
            price = p;
            orderrep = o;
            resserv = rs;
            resrepo = rr;
        }
        public ActionResult Contact()
        {
            return View();
        }
        
        public ActionResult Index()
        {
            var ggun = gunrepo.GetAllGuns();
            var model = new IndexPageViewModel()
            {

                Guns = gunrepo.GetAllGuns().ToDictionary(x => x.Id),
                ReservedGuns = ggun.Where(p => resserv.GunIsOccupied(p)).Select(p => p.Id).ToList()
            };
            return View(model);
        }
       public ActionResult ReserveGun(int gunId)
        {
            var ggun = gunrepo.GetGun(gunId);
            var date = DateTime.Now;
            var parameters = new PriceCalculationParameters()
            {
                gun = ggun
            };

            var reservation = resserv.Reserve(ggun);

            var model = new ReservationViewModel()
            {
                Reservation = reservation,
                gun = ggun,
                PriceComponents = price.CalculatePrice(parameters),
                Date = date,              
            };
            return View(model);
        }

        public ActionResult GunPage(int Id,bool Tracer ,bool Hollowpoint,bool Incendiary,string firstName, string lastName,int resId)
        {
            var ggun = gunrepo.GetGun(Id);
            var parameters = new PriceCalculationParameters()
            {
                gun = ggun,
                Tracer = Tracer,
                Hollowpoint = Hollowpoint,
                Incendiary = Incendiary
            };
            var model = new IndexPageViewModel()
            {

                _Gun = gunrepo.GetGun(Id),
                PriceComponents = price.CalculatePrice(parameters)
            };
            var order = new Order();
            order.FirstName = firstName;
            order.LastName = lastName;
            order.GunId = Id;
            this.orderrep.Create(order);
            Gun gun = gunrepo.GetGun(Id);
            gunrepo.UpdateCount(gun);
            Reservation reservation = resrepo.Get(resId);
            resserv.RemoveReservation(reservation);
            return View(model);
        }
      
        public ActionResult BuyGun()
        {
            return RedirectToAction("Index", "Gun");

        }

    }
}

GunShop/Controllers/WarehouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GunShop.Domain.Core;
using GunShop.Domai.Interfaces;
using GunShop.Services.Interfaces;
using GunShop.Models;

namespace GunShop.Controllers
{
    public class WarehouseController : Controller
    {
        private  IGunRepository repo;
        private IPriceCalculation price;
        private IOrderRepository orderrep;
        private IWarehouseRepository ware;
        public WarehouseController(IGunRepository r, IPriceCalculation p, IOrderRepository o,IWarehouseRepository w)
        {
            repo = r;
            price = p;
            orderrep = o;
            ware = w;
        }
        public ActionResult Warehouses()
        {
            var model = new IndexPageViewModel()
            {

                Ware = ware.GetAllWarehouses().ToDictionary(x => x.Id)
            };
            return View(model);

        }
            public ActionResult WarehouseGuns(int Id)
        {
            var model = new IndexPageViewModel()
            {

                Gun = repo.SelectionByWarehouse(Id)

            };           
            return View(model);
        }
        public ActionResult GunPage(int id)
        {
            return RedirectToAction("GunPage", "Gun", new { id = id });
        }
        
        
    }
}

GunShop/Views/Gun/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    
    Kyiv, Politehnichna 6<br />
    <abbr title="Phone">P:</abbr>
    0442023576
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
   
</address>

GunShop/Views/Gun/GunPage.cshtml
@model GunShop.Models.IndexPageViewModel

<h2>Gun @Model._Gun.Type</h2>

<h4>Price:</h4>
@foreach (var pc in Model.PriceComponents)
{
    <span>@pc.Name:@pc.Value$</span>
    <br />
}
<h5>Total Price: @Model.PriceComponents.Select(x => x.Value).Sum()$ </h5>
@Html.ActionLink("Return", "BuyGun")

GunShop/Views/Gun/Index.cshtml
@model GunShop.Models.IndexPageViewModel

@{
    ViewBag.Title = "Index";
}
    <head>
        <script 
                type = "text/javascript">
            function SearchScript() {
                var input, filter, ul, li, a, i;
                input = document.getElementById("mySearch");
                filter = input.value.toUpperCase();
                ul = document.getElementById("myMenu");
                li = ul.getElementsByTagName("li");
                for (i = 0; i < li.length; i++) {
                    a = li[i].getElementsByTagName("a")[0];
                    if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        li[i].style.display = "";
                    } else {
                        li[i].style.display = "none";
                    }
                }
            }

</script>
    </head>
<style>
    h {
        font-family: 'Times New Roman', Times, serif; /* Шрифт с засечками */
        font-style: italic; /* Курсивное начертание */
    }
</style>
<body>
    <h2>Search section</h2>
    <input type="text" id="mySearch" onkeyup="SearchScript()" placeholder="Search.." title="Type in a category">
    <ul id="myMenu">
        <li><a href="@Url.Action("Warehouses","Warehouse")">Warehouses</a></li>
        <li><a href="@Url.Action("Index","Gun")">Guns</a></li>
        <li><a href="@Url.Action("Contact","Gun")">Contact</a></li>

    </ul>
    <link rel="stylesheet" href="~/Content/Search.css">
  <div>
    <h2>Available guns</h2>


            @foreach (var gun in Model.Guns) {

            <h>@gun.Value.Type in warehouse @gun.Value.InStock </h>
                if (Model.ReservedGuns.Contains(gun.Value.Id))
                {
             @gun.Value.Id;
                }
                else {
  <a href="@Url.Action("ReserveGun", new { gunId = gun.Value.Id })" > Choose </a>
                 }           
   }
  </div>}
    
</body>
       

GunShop/Views/Gun/Order.cshtml
@model GunShop.Models.BuyModel

@{ ViewBag.Title = "Order details"; }

<h2>Gun @Model.Gun.Type </h2>
<


<h4>Additional bullets:</h4>
@foreach (var pc in Model.PriceComponents.ToList())
{
<span>@pc.Name:@pc.Value$</span>
                <br />}

<h5>Total Price: @Model.PriceComponents.Select(x => x.Value).Sum(); </h5>

GunShop/Views/Gun/ReserveGun.cshtml
@model GunShop.Models.ReservationViewModel

<h2>Gun @Model.gun.Type</h2>
<h4>Reserve starts at @Model.Date.ToString("dd.MM.yy hh:mm")</h4>

<h2>the gun @Model.gun.Type is reserved for you for</h2>

<h4>Price:</h4>

@foreach (var pc in Model.PriceComponents)
{
    <span>@pc.Name:@pc.Value$</span>
    <br />
}

@using (Html.BeginForm("GunPage", "Gun", FormMethod.Post))
{
    <input type="hidden" value="@Model.gun.Id" name="Id" />
    <input type="hidden" value="@Model.Reservation.Id" name="resId" />
    <table>
        <tr>
            <td>First Name</td>
            <td><input type="text" name="firstName" /></td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td><input type="text" name="lastName" /></td>
        </tr>
        <tr>
            <td>Tracer</td>         
            <td>@Html.CheckBox("Tracer")</td>
        </tr>
        <tr>
            <td>Hollowpoint</td>
            <td>@Html.CheckBox("Hollowpoint")</td>
        </tr>
        <tr>
            <td>Incendiary</td>
            <td>@Html.CheckBox("Incendiary")</td>
        </tr>
    </table>
    <input type="submit" value="submit" />
}

GunShop/Views/Home/Index.cshtml
@model GunShop.Models.IndexPageViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Available guns</h2>
@foreach (var gun in Model.Guns)
{
    <a href="@Url.Action("Gun",new {id = gun.Value.Id})">@gun.Value.Type </a>
    <br />

   
    
}

GunShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GunShop", "Index", "Gun", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                  
                    <li>@Html.ActionLink("Warehouses", "Warehouses", "Warehouse")</li>
                    <li>@Html.ActionLink("Contact us", "Contact", "Gun")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Kliuha,Petrenko,Semenov</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GunShop/Views/Warehouse/WarehouseGuns.cshtml
@model GunShop.Models.IndexPageViewModel

@{
    ViewBag.Title = "WarehouseGuns";
}

<h2>WarehouseGuns</h2>
@foreach (var gun in Model.Gun)
{
    <h>@gun.Type </h>
    @Html.ActionLink("Buy", "ReserveGun", new { gunid = gun.Id })
    <br />
}

GunShop/Views/Warehouse/Warehouses.cshtml
@model GunShop.Models.IndexPageViewModel

@{
    ViewBag.Title = "Warehouses";
}

<h2>Available warehouses</h2>
@foreach (var ware in Model.Ware)
{
    <h>@ware.Value.Name </h>
    @Html.ActionLink("Choose", "WarehouseGuns", new { id = ware.Value.Id })
    <br />
}